### ISSUE TITLE
검투사 제작

### ISSUE THREAD

**Issue by blu3fishez** [blu3fishes/roguelike-pvp#2]
# 검투사

## 요약

- 할버드, 삼지창, 표창을 사용하는 웨폰마스터 컨셉

- 흡수스킬 + 트루딜링 돌진기를 통해 방어를 무력화 시키는 안티 탱커 / 표준 딜러

## 딜 구조

- 극딜 : 지속 딜 = 6 : 4
- 딜링능력에 치중된 지속 근접딜러
- 기초 체력은 높으나(22) 방어력이 전무(0/0)

## 컨셉
  - 할버드 돌진을 통해 '방어무시' 공격을 할 수 있다.
  - 할버드 돌진을 하면 맞춘 플레이어의 수에 따라 스킬의 쿨타임이 줄어든다. (2명 맞출 경우 100%, 1명 맞출 경우 50% 감소)
  - 할버드의 궁극기와 삼지창을 이용해 비가 올 경우에 날아오를 수 있다.
  - 삼지창은 던질 수 없지만 물 속에서는 날아다닐 수 있는 능력이 있다.
  - 표창은 우클릭을 통해 마법 표창을 3개 날릴 수 있다. 마법 삼지창은 적중시 자신의 HP를 재생한다.

  - 중요 콤보 : 궁 -> 표창 -> 할버드 돌진 -> 할버드 평타 -> 삼지창 날아오르기
  - 물 있을 때 콤보 : 궁 -> 표창 -> 삼지창 돌진 -> 할버드 돌진 -> 할버드 평타 -> 삼지창 날아오르기
  - 핵심 콤보 : 궁 + 표창 + 돌진 3개를 모두 적중시 트루데미지 + 재생이라는 큰 버프를 획득한다.

****
## 기초 능력치

기초체력 : 22 (조금 높음)
기초이동속도 : 0.103 (조금 빠름)
기초방어력 : 0/0 (근접 / 딜러)

## 무기

1. 디미나이트 할버드 : 근접 데미지 (10). 우클릭으로 돌진을 통해 광역기 발생.

2. 삼지창 : 근접 데미지 (12). 자신이 젖은 상태라면 날아오를 수 있음.

3. 마법 흡능 수리검 : 근접데미지 없음. 우클릭 시 특수 표창 발사 쿨타임 20초, 공격 성공 시 재생 버프 획득
****
### 투사의 돌진  (?)
우클릭을 누르면 전방으로 6칸 돌진하여 피해를 입힌다.  
피해는 6으로 고정 데미지를 입힌다.

### 심해의 아우성 (60)
F 키를 누르면 비를 30초간 내리게 하고 자신을 제외한 모든 이들에게 낙뢰를 떨군다.
****

### 마법 흡능 수리검
- 공격력
### 흡능의 수리검 (14)
우클릭을 누르면 전방을 향해 흡능의 마법 수리검을 3개 던진다. (데미지는 수리검의  (부채꼴 형태)  
수리검에 피격이 성공할 시 검투사는 재생 III (4) 를 획득한다.

- 레퍼런스
할버드 우클릭 : 돌진  /playsound minecraft:entity.guardian.death master @a ~ ~ ~ 1 1.8

마법표창 우클릭 /playsound minecraft:entity.guardian.death master @a ~ ~ ~ 1 1.8 (3번)

**Comment by blu3fishez** [comment]
클래스 카드 (기획 시 사용할 템플릿) 한번 만들어서 정형화 시켜야함

**Comment by lees2541** [comment]
전체공격기는 쿨 말고 다른조건 만드는 게 좋을듯

그리고 세 무기의 외형적인 부분은 진짜 다르게 해야함

최소한 맞는사람 입장에선 뭐에 맞았는지 알게

**Comment by lees2541** [comment]
할버드랑 삼지창 뭐가 다른 지 모르겠음
개성있는 여러무기를 다루는 웨폰마스터가 아니라 그냥 다른스킬 매개체로의 차이밖에 안보임

**Comment by lees2541** [comment]
수리검은 잼서보이네
