### ISSUE TITLE
역할군 분류

### ISSUE THREAD

**Issue by blu3fishez** [blu3fishes/roguelike-pvp#3]
# 역할군

## 전사
높은 공격속도를 통하여 광전사적인 플레이를 하는 직업군이다. 그러나 이동속도에 있어 패널티를 받는다. 

`장점`
- 높은 공격속도로 적을 교란 시킨다.
- 체력도 탱커 다음으로 높으며 딜링 능력도 겸비한 밸런스형이다.

`단점`
- 이동 속도가 느린 뚜벅이다.
- 원거리 대체능력이 전무하다.

##  마법사 
트루대미지 기반 마법으로 방어력을 뚫으며, 동시에 조건부 파티 유틸을 확보한다.

`장점`
- 방어력 무시 트루데미지를 넣을 수 있다.
- 원거리 딜리와 동시에 안정적으로 딜을 넣을 수 있는 직업군이다.
- 딜러 중 무적/보호막 기가 있다.

`단점`
- 체력이 제일 낮으며, 암살자보다 불안정한 생존력을 갖춘다.
- 이동 스킬이 존재하지만 자체 이동속도는 낮은 편이다.

## 암살자
[**힘 버프**](https://minecraft.fandom.com/wiki/Strength)를 통해 순간딜링능력을 극대화하는 플레이를 한다.

`장점`
- 순간 극딜 능력은 안정성 대비 최상위이다.
- 풍부한 돌진/이동 스킬로 적에게 도주하기 쉬우며 교란시키기도 쉽다.

`단점`
- 방어력에 취약하다. (생명력은 높으나 방어력이 낮게 설계된다.)
- 스킬의존도가 높아 안정적인 딜링 수단이 적거나 없다.

## 원거리 딜러
적당한 생존 능력을 갖추며, 동시에 공격력이 높은게 특징인 역할군이다.
원거리에서 공격하여 제일 안정적으로 딜링을 할 수 있다.

`장점`
- 안정적인 딜링 스킬이나 수단이 존재한다.
- 공격형 역할군 중 장기전에 제일 유리하다.

`단점`
- 무적기/보호막 스킬이 없다.
- 돌진 스킬이 없다.

## 탱커
높은 체력과 방어력을 기반으로 교전시간이 제일 길다. 따라서 교전 시 생각할 시간이 제일 많아 두뇌플레이에 유리하며, 딜링 기술을 차단/방어 할 수 있는 능력이 있어 안티-메타 로 사용할 수 있는 역할군이다.

`장점`
- 높은 방어력, 체력을 기반으로 팀의 방패 역할을 도모할 수 있다.
- 대부분의 탱커는 데미지를 방어/무효화할 수 있다.

`단점`
- 딜링 스킬이 없거나 제한적이다.
- 순간이동/돌진 스킬이 없다.
- 이동속도가 느리다.

**Comment by blu3fishez** [comment]
위 역할군이 맞는지, 아니면 뭔가 다른 이견이 있는지 물어봐줄 사람 구함

마법사 같은 경우는 커스텀 데미지 들여와서 만들거고 대응용 룬도 만들거긴 함

**Comment by lees2541** [comment]
적당
